1
OksanaVM/java-filmorate pull request #4
Opened 2023-02-06 20:32 UTC by OksanaVM

2023-02-07 15:40 UTC, boristm1 requested changes

2023-02-07 15:40 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandlerController.java
> +    public Map<String, String> handlerInternalException(final InternalException e) {
этот обработчик бесполезен, т. к. все исключения наследуются от Throwable, а на Throwable уже есть точно такой же обработчик

2023-02-07 15:40 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandlerController.java
> +    public ResponseEntity<String> handlerValidate(ConstraintViolationException e) {
этот обработчик не нужен - при ошибки валидации аргументов в контроллерах возникает другое исключение: org.springframework.web.bind.MethodArgumentNotValidException, но для него обработчик можно не делать, т. к. они автоматом получают код 400

2023-02-07 15:40 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandlerController.java
> +    public Map<String, String> handlerThrowable(final Throwable e) {
этот обработчик можно не делать, т. к. все остальные исключения автоматом получают код 500

2023-02-07 15:40 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +            throw new ObjectNotFoundException("User с id " + id + " не найден");
это исключение относится к бизнес-логике, и поэтому его лучше выбрасывать в сервисах (т. к. именно сервисный слой отвечает за бизнес-логику)

2023-02-07 15:40 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            throw new ObjectNotFoundException("Фильм с id=" + id + " не найден");
это исключение относится к бизнес-логике, и поэтому его лучше выбрасывать в сервисах (т. к. именно сервисный слой отвечает за бизнес-логику)

2023-02-07 15:40 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +import ru.yandex.practicum.filmorate.model.exeption.ValidationException;
не используется

2023-02-07 15:40 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/model/exeption/ValidationException.java
> +public class ValidationException extends RuntimeException {
похоже, нигде не используется - лучше удалить

2023-02-07 15:40 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        users.get(firstId).getFriends().remove(secondId);
если нет юзеров с firstId или secondId, будет NPE

2023-02-07 15:40 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public List<Integer> addFriendship(int firstId, int secondId) {
параметры лучше переименовать в userId и friendId, иначе не понятно, чьи это id

2023-02-07 15:40 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        } else {
позволяет добавить самого себя в друзья

2023-02-07 15:40 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public Film addLike(int filmId, int userId) {
позволяет добавить лайк с id несуществующего юзера

2023-02-09 12:27 UTC, OksanaVM commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public List<Integer> addFriendship(int firstId, int secondId) {
исправила, немного не так.

2023-02-09 12:28 UTC, OksanaVM commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        users.get(firstId).getFriends().remove(secondId);
вроде исправила

2023-02-09 12:28 UTC, OksanaVM commented on src/main/java/ru/yandex/practicum/filmorate/model/exeption/ValidationException.java
> +public class ValidationException extends RuntimeException {
удалила

2023-02-09 12:28 UTC, OksanaVM commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            throw new ObjectNotFoundException("Фильм с id=" + id + " не найден");
исправила

2023-02-09 12:28 UTC, OksanaVM commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +            throw new ObjectNotFoundException("User с id " + id + " не найден");
исправила

2023-02-09 12:29 UTC, OksanaVM commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandlerController.java
> +    public Map<String, String> handlerThrowable(final Throwable e) {
оставила

2023-02-09 12:29 UTC, OksanaVM commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandlerController.java
> +    public ResponseEntity<String> handlerValidate(ConstraintViolationException e) {
убрала

2023-02-09 12:29 UTC, OksanaVM commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandlerController.java
> +    public Map<String, String> handlerInternalException(final InternalException e) {
исправила

2023-02-09 12:29 UTC, OksanaVM commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public Film addLike(int filmId, int userId) {
исправила?

2023-02-09 12:29 UTC, OksanaVM commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        } else {
справила?

2023-02-10 11:45 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandlerController.java
> +    public Map<String, String> handlerThrowable(final Throwable e) {
тогда нужно определить обработчик и для org.springframework.web.bind.MethodArgumentNotValidException, иначе этот глушит MethodArgumentNotValidException, и при ошибке валидации отдает 500, а не 400.
Либо

2023-02-10 12:09 UTC, boristm1 requested changes

2023-02-10 12:09 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandlerController.java
> +    /*@ExceptionHandler
закомментированный код лучше убрать - везде - из всех классов - все есть в истрии гита, если понадобится восстановить

2023-02-10 12:09 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.getAllUsers().containsKey(user.getId())) {
лучше проверить, что getById  == null (и по имени метода не очевидно, что getAllUsers возвращает Map)

2023-02-10 12:09 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandlerController.java
> +import com.sun.jdi.InternalException;
все неиспользуемые импорты лучше убрать

2023-02-10 12:09 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getName() == null || user.getName().isBlank())
не хватает скобок {}

2023-02-10 12:09 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            throw new ObjectNotFoundException("Пользователь не может добавть в друзья сам себя");
в этом случае будет 404, а лучше отдать 400, т. к. это неверные данные переданы в запрос, а не что-то не найдено

2023-02-10 12:09 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public void update(User user) {
при обновлении тоже нужно делать validate(user);

2023-02-10 12:09 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private boolean validate(User user) {
нужно еще проверить, что логин не содержит пробелов и вернуть 400 (кинуть исключение, которое будет связано с кодом 400, либо сделать свой валидатор на этот случай)

2023-02-10 12:09 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film != null && userId > 0) {
а если userId > 0, но такого юзера нет?

2023-02-10 12:09 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            throw new ObjectNotFoundException("Фильм с id=" + id + " не найден");
все выбросы ObjectNotFoundException нужно перенести в сервисы

2023-02-10 12:09 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +            throw new ObjectNotFoundException("User с id=" + id + " не найден");
все выбросы ObjectNotFoundException нужно перенести в сервисы

2023-02-11 19:52 UTC, OksanaVM commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandlerController.java
> +    public Map<String, String> handlerThrowable(final Throwable e) {
определила

2023-02-11 19:53 UTC, OksanaVM commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public void update(User user) {
исправила

2023-02-11 19:53 UTC, OksanaVM commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private boolean validate(User user) {
исправила

2023-02-12 19:47 UTC, boristm1 approved these changes

2023-02-12 19:47 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandlerController.java
> +    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
INTERNAL_SERVER_ERROR дает код 500, а нужен 400

2023-02-12 19:47 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    Map<Integer, User> getAllUsers();
по имени метода не очевидно, что он возвращает Map + не понятно, что является ключом (не очевидно, что это id пользователя) + будет сложно это перевести на БД - лучше Map вообще из хранилищ не возвращать (можно обойтись findAll и getById)

2023-02-12 19:47 UTC, boristm1 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.getLikes().add(user.getId());
если фильма нет, будет NPE

2023-02-13 13:38 UTC, merged